repos:
  - repo: https://github.com/pycqa/pylint
    rev: "v2.14.5"
    hooks:
      - id: pylint
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        args: ["--rcfile=./backend/.pylintrc"]
        additional_dependencies: [
            # pylint dependency
            pylint_django,
            django,
            djangorestframework,
            drf_yasg
          ]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
