repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile, black, --skip, migrations]
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        additional_dependencies: [flake8-django==1.4.0]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy # It will read mypy.ini automatically
        args: ["--config-file=./mypy.ini"]
        additional_dependencies:
          - types-pytz
          - types-redis
          - django-stubs
