version: '3'
services:
  backend:
    image: ghcr.io/bocabitlabs/buho-stocks:latest
    container_name: buho-backend
    restart: always
    command: daphne -b 0.0.0.0 -p 8000 buho_backend.asgi:application
    volumes:
      - logs:/app/logs
      - static:/app/static
      - media:/app/media
    env_file:
      - ./.env.prod
    environment:
      - DJANGO_ENV=prod
    expose:
      - 8000
    depends_on:
      - redis
      - db
  redis:
    image: redis:7
    container_name: buho-redis
    expose:
      - 6379
  celery:
    image: ghcr.io/bocabitlabs/buho-stocks:latest
    container_name: buho-celery
    restart: always
    command: celery -A buho_backend.celery_app:app worker -l info
    volumes:
      - logs:/app/logs
      - static:/app/static
      - media:/app/media
    env_file:
      - ./.env.prod
    environment:
      - DJANGO_ENV=prod
    depends_on:
      - db
      - redis
  client:
    image: ghcr.io/bocabitlabs/buho-stocks-client:latest
    container_name: buho-client
    restart: always
    env_file:
      - ./.env.prod
    environment:
      - NGINX_PORT=8080
    ports:
      - 8080:80
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - backend
  db:
    image: mariadb:10
    container_name: buho-db
    expose:
      - 3306
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  static:
  media:
  logs: