version: '3'
services:
  backend:
    build: .
    restart: always
    command: gunicorn buho_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./volumes/logs:/app/logs
      - ./volumes/static:/app/static
      - ./volumes/media:/app/media
    env_file:
      - ./.env.prod
    environment:
      - DJANGO_ENV=prod
    expose:
      - 8000
    depends_on:
      - redis
      - db
  redis:
    image: redis:7
#   celery:
#     build: .
#     restart: always
#     command: celery -A config worker -l info
#     volumes:
#       - .:/code
#     env_file:
#       - ./.env
#     depends_on:
#       - db
#       - redis
#       - web
  client:
    build:
      context: .
      dockerfile: docker.client.Dockerfile
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./volumes/static:/app/static
      - ./volumes/media:/app/media
    depends_on:
      - backend
  db:
    image: mariadb:10
    restart: always
    volumes:
      - ./volumes/mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DB: ${DB_NAME}
