version: '3.8'
services:
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    image: buho-stocks-docker
    command: ["python", "manage.py", "migrate"]
    volumes:
      - ./backend:/usr/src/backend
      - ./data/:/usr/src/data
  app:
    image: buho-stocks-docker
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
    - 8000:8000
    volumes:
    - ./backend:/usr/src/backend
    - ./data/:/usr/src/data
    depends_on:
        - migration
