version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buho-backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
    - 8000:8000
    volumes:
    - ./requirements.txt:/usr/src/backend/requirements.txt
    # - ./static_my_project:/static_my_project
    - ./src:/usr/src/backend
    - ./data/:/usr/src/data
    - ./config:/usr/src/backend/config