name: React CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: client/yarn.lock
      - name: Install Dependencies
        run: |
          cd client && yarn
          mv client/src/config.sample.js client/src/config.js
      - name: Lint
        run: |
          cd client && yarn lint
      - name: Run Tests
        run: |
          cd client && yarn test --coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v1
